# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='anticoagulant',
            field=models.CharField(blank=True, max_length=4, null=True, choices=[(b'NaCH', b'Sodium Citrate')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='blood_pressure',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='blood_pressure_unit',
            field=models.CharField(blank=True, max_length=3, null=True, choices=[(b'mmHg', b'Millimeters of Mercury')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='haemoglobin',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='haemoglobin_unit',
            field=models.CharField(blank=True, max_length=3, null=True, choices=[(b'g/L', b'Gram per Liter')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='height',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='height_unit',
            field=models.CharField(blank=True, max_length=3, null=True, choices=[(b'cm', b'Centimeters'), (b'ft', b'Feet')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='hospital_batch_no',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='is_nbts_approved',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='is_taken',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='nbts_batch_no',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='weight',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='blood',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=3, null=True, choices=[(b'kg', b'Kilograms'), (b'lb', b'Pounds')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, max_length=2, null=True, choices=[(b'A', b'A'), (b'B', b'B'), (b'O', b'O'), (b'AB', b'AB')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_rh_positive',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='advised_against_giving',
            field=models.BooleanField(default=False, verbose_name=b'Ever been advised not to give blood?', choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='anaemia',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='blood_pressure_issue',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='bowel_disease',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='cancer',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='diabetes',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='growth_hormone',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='head_injury',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='jaundice',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='kidney_problem',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='malaria',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='neurosurgical_procedure',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='serious_illness',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='tigason',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionforma',
            name='transplant',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='cuts',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='dental_work',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='ever_pregnant',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='feeling_healthy',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='gastric_upset',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='pain_killers',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_abattoir',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_chest_pain',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_chicken_pox',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_immunizations',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_medication',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_pregnancy',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_sexual_infection',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_skin_condition',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='recent_unwellness',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformb',
            name='risk_of_injury_activities',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='aids',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='blood_transfusion',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='clotting_factors',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='hepatitis',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='injured_with_needle',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='sex_with_above',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='swollen_glands',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='tatoo',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionformc',
            name='unprescibed_injection',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionpreform',
            name='is_first_donation',
            field=models.BooleanField(default=True, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionpreform',
            name='last_donation_date',
            field=models.DateField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='donorconditionpreform',
            name='last_donation_place',
            field=models.CharField(max_length=150, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='adverse_antibodies',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='blood_group_antibodies',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='blood_type_crossmatch',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='chagas',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='hepatitis_B',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='hepatitis_C',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='hiv1',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='hiv2',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='htlv_I',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='htlv_II',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='infectious_agents',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='syphillis',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hospitaltest',
            name='west_nile',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='adverse_antibodies',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='blood_group_antibodies',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='blood_type_crossmatch',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='chagas',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='hepatitis_B',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='hepatitis_C',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='hiv1',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='hiv2',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='htlv_I',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='htlv_II',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='infectious_agents',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='syphillis',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='nbtstest',
            name='west_nile',
            field=models.BooleanField(default=False, choices=[(True, b'Yes'), (False, b'No')]),
            preserve_default=True,
        ),
    ]
