from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'apps.donations.views.list', name='list'),
    # url(r'^add/$', 'apps.donations.views.add', name='add_donation'),
    url(r'^(?P<blood_id>[0-9]+)/$', 'apps.donations.views.blood',
        name='blood'),
    url(r'^(?P<blood_id>[0-9]+)/hospital-tests/$',
        'apps.donations.views.hospital', name='hospital'),
    url(r'^(?P<blood_id>[0-9]+)/nbts-tests/$',
        'apps.donations.views.nbts', name='nbts'),
    url(r'^(?P<blood_id>[0-9]+)/pre-form/$',
        'apps.donations.views.pre_form', name='pre_form'),
    url(r'^(?P<blood_id>[0-9]+)/form-A/$',
        'apps.donations.views.form_a', name='form_a'),
    url(r'^(?P<blood_id>[0-9]+)/form-B/$',
        'apps.donations.views.form_b', name='form_b'),
    url(r'^(?P<blood_id>[0-9]+)/form-C/$',
        'apps.donations.views.form_c', name='form_c'),
    url(r'^(?P<blood_id>[0-9]+)/donor/$',
        'apps.donations.views.donor', name='blood_donor'),

    url(r'^donors/$', 'apps.donations.views.donors', name='donors'),
    # url(r'^donors/add$', 'apps.donations.views.add_donor', name='add_donor'),

    url(r'^donors/donate/$', 'apps.donations.views.donate_details',
        name='donate_details'),
    url(r'^donors/donate/thankyou$', 'apps.donations.views.donate_thankyou',
        name='donate_thankyou'),
    url(r'^donors/donate/(?P<blood_id>[0-9]+)/pre-form$',
        'apps.donations.views.donate_pre_form', name='donate_pre_form'),
    url(r'^donors/donate/(?P<blood_id>[0-9]+)/formA$',
        'apps.donations.views.donate_form_a', name='donate_form_a'),
    url(r'^donors/donate/(?P<blood_id>[0-9]+)/formB$',
        'apps.donations.views.donate_form_b', name='donate_form_b'),
    url(r'^donors/donate/(?P<blood_id>[0-9]+)/formC$',
        'apps.donations.views.donate_form_c', name='donate_form_c'),

    url(r'^donors/(?P<donor_id>[0-9]+)/$', 'apps.donations.views.donor',
        name='donor'),
    url(r'^donors/(?P<donor_id>[0-9]+)/donations/$',
        'apps.donations.views.donor_donations', name='donor_donations'),
)
